"use client";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeProvider";
import { motion, useScroll, useSpring } from "framer-motion";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/page";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
  style: ["normal"],
  variable: "--font-inter",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
  style: ["italic", "normal"],
  variable: "--font-poppins",
});

// export const metadata: Metadata = {
//   title: "Favour Idoko",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { scrollYProgress } = useScroll();
  const scaleX = useSpring(scrollYProgress, {
    stiffness: 100,
    damping: 30,
    restDelta: 0.001,
  });
  return (
    <html lang="en">
      <body
  className={`bg-stars min-h-screen flex flex-col relative ${inter.className} ${poppins.className}`}
>
  <div className="absolute inset-0 bg-black/70 z-0 pointer-events-none" />
  <motion.div
    style={{ scaleX }}
    className="fixed bottom-0 left-0 right-0 h-[8px] bg-[#EAB308] transform origin-left z-50"
  />
  <div className="relative z-10">
    <Header />
  </div>
  <main className="flex-1 relative p-4">
    <ThemeProvider>{children}</ThemeProvider>
  </main>
  <div className="relative">
    <Footer />
  </div>
</body>

    </html>
  );
}
