"use client";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeProvider";
import { motion, useScroll, useSpring } from "framer-motion";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/page";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
  style: ["normal"],
  variable: "--font-inter",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
  style: ["italic", "normal"],
  variable: "--font-poppins",
});

// export const metadata: Metadata = {
//   title: "Favour Idoko",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { scrollYProgress } = useScroll();
  const scaleX = useSpring(scrollYProgress, {
    stiffness: 100,
    damping: 30,
    restDelta: 0.001,
  });
  return (
    <html lang="en">
      <body className={`${inter.className} ${poppins.className}`}>
        <div className="bg-stars relative min-h-screen overflow-hidden">
          {/* Overlay */}
          <div className="absolute inset-0 bg-black/70 z-0" />

          {/* Content */}
          <div className="relative z-10">
            <motion.div
              style={{ scaleX }}
              className="fixed bottom-0 left-0 right-0 h-[8px] bg-[#EAB308] transform origin-left z-50"
            />
            <Header />
            <ThemeProvider>{children}</ThemeProvider>

            {/* <Contact /> */}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
